export const examMap = {
  CAT: {
    QUANT: {
      ALGEBRA: {
        COORDINATE_GEOMETRY: "CAT/QUANT/ALGEBRA/COORDINATE_GEOMETRY",
        FUNCTIONS: "CAT/QUANT/ALGEBRA/FUNCTIONS",
        LINEAR_EQUATIONS: "CAT/QUANT/ALGEBRA/LINEAR_EQUATIONS",
        QUADRATIC_EQUATIONS: "CAT/QUANT/ALGEBRA/QUADRATIC_EQUATIONS",
        INEQUALITIES: "CAT/QUANT/ALGEBRA/INEQUALITIES",
        LOGARITHMS_MODULUS: "CAT/QUANT/ALGEBRA/LOGARITHMS_MODULUS",
        SEQUENCES_SERIES: "CAT/QUANT/ALGEBRA/SEQUENCES_SERIES",
        MINIMA_MAXIMA: "CAT/QUANT/ALGEBRA/MINIMA_MAXIMA",
        POLYNOMIAL_EQUATIONS: "CAT/QUANT/ALGEBRA/POLYNOMIAL_EQUATIONS",
      },
      ARITHMETICS: {
        PERCENTAGE_PROFIT_LOSS: "CAT/QUANT/ARITHMETICS/PERCENTAGE_PROFIT_LOSS",
        RATIO_PROPORTION: "CAT/QUANT/ARITHMETICS/RATIO_PROPORTION",
        TIME_WORK: "CAT/QUANT/ARITHMETICS/TIME_WORK",
        TIME_SPEED_DISTANCE: "CAT/QUANT/ARITHMETICS/TIME_SPEED_DISTANCE",
        AVERAGES: "CAT/QUANT/ARITHMETICS/AVERAGES",
        SIMPLE_COMPOUND_INTEREST:
          "CAT/QUANT/ARITHMETICS/SIMPLE_COMPOUND_INTEREST",
        MIXTURES_ALLEGATIONS: "CAT/QUANT/ARITHMETICS/MIXTURES_ALLEGATIONS",
      },
      GEOMETRY_AND_MENSURATION: {
        LINES_ANGLES: "CAT/QUANT/GEOMETRY_AND_MENSURATION/LINES_ANGLES",
        TRIANGLES: "CAT/QUANT/GEOMETRY_AND_MENSURATION/TRIANGLES",
        CIRCLES: "CAT/QUANT/GEOMETRY_AND_MENSURATION/CIRCLES",
        QUADRILATERALS: "CAT/QUANT/GEOMETRY_AND_MENSURATION/QUADRILATERALS",
        MENSURATION_2D: "CAT/QUANT/GEOMETRY_AND_MENSURATION/MENSURATION_2D",
        MENSURATION_3D: "CAT/QUANT/GEOMETRY_AND_MENSURATION/MENSURATION_3D",
      },
      MODERN_MATH: {
        SETS_VENN_DIAGRAMS: "CAT/QUANT/MODERN_MATH/SETS_VENN_DIAGRAMS",
        PROBABILITY: "CAT/QUANT/MODERN_MATH/PROBABILITY",
        PERMUTATION_COMBINATION:
          "CAT/QUANT/MODERN_MATH/PERMUTATION_COMBINATION",
        NUMBER_THEORY: "CAT/QUANT/MODERN_MATH/NUMBER_THEORY",
      },
      NUMBERS: {
        DIVISIBILITY_RULES: "CAT/QUANT/NUMBERS/DIVISIBILITY_RULES",
        PRIME_NUMBERS: "CAT/QUANT/NUMBERS/PRIME_NUMBERS",
        HCF_LCM: "CAT/QUANT/NUMBERS/HCF_LCM",
        REMAINDERS: "CAT/QUANT/NUMBERS/REMAINDERS",
      },
    },
    LRDI: {
      DATA_INTERPRETATION: {
        TABLES: "CAT/LRDI/DATA_INTERPRETATION/TABLES",
        GRAPHS: "CAT/LRDI/DATA_INTERPRETATION/GRAPHS",
        CASELETS: "CAT/LRDI/DATA_INTERPRETATION/CASELETS",
      },
      LOGICAL_REASONING: {
        ARRANGEMENTS: "CAT/LRDI/LOGICAL_REASONING/ARRANGEMENTS",
        PUZZLES: "CAT/LRDI/LOGICAL_REASONING/PUZZLES",
        BLOOD_RELATIONS: "CAT/LRDI/LOGICAL_REASONING/BLOOD_RELATIONS",
      },
    },
    VARC: {
      READING_COMPREHENSION: "CAT/VARC/READING_COMPREHENSION",
      PARA_JUMBLES: "CAT/VARC/PARA_JUMBLES",
      PARA_SUMMARY: "CAT/VARC/PARA_SUMMARY",
      GRAMMAR: "CAT/VARC/GRAMMAR",
      VOCABULARY: "CAT/VARC/VOCABULARY",
    },
  },

  NMAT: {
    LANGUAGE_SKILLS: "NMAT/LANGUAGE_SKILLS",
    QUANTITATIVE_SKILLS: "NMAT/QUANTITATIVE_SKILLS",
    LOGICAL_REASONING: "NMAT/LOGICAL_REASONING",
  },

  SNAP: {
    GENERAL_ENGLISH: "SNAP/GENERAL_ENGLISH",
    ANALYTICAL_LOGICAL_REASONING: "SNAP/ANALYTICAL_LOGICAL_REASONING",
    QUANTITATIVE_DATA_INTERPRETATION: "SNAP/QUANTITATIVE_DATA_INTERPRETATION",
  },

  XAT: {
    DECISION_MAKING: "XAT/DECISION_MAKING",
    QUANTITATIVE_APTITUDE: "XAT/QUANTITATIVE_APTITUDE",
    VERBAL_ABILITY: "XAT/VERBAL_ABILITY",
  },

  CET_MAH: {
    LOGICAL_REASONING: "CET_MAH/LOGICAL_REASONING",
    ABSTRACT_REASONING: "CET_MAH/ABSTRACT_REASONING",
    QUANTITATIVE_APTITUDE: "CET_MAH/QUANTITATIVE_APTITUDE",
  },

  PGDBA: {
    VERBAL_ABILITY: "PGDBA/VERBAL_ABILITY",
    LOGICAL_REASONING: "PGDBA/LOGICAL_REASONING",
    QUANTITATIVE_APTITUDE: "PGDBA/QUANTITATIVE_APTITUDE",
  },

  SRCC: {
    GENERAL_AWARENESS: "SRCC/GENERAL_AWARENESS",
    BUSINESS_AWARENESS: "SRCC/BUSINESS_AWARENESS",
    LOGICAL_REASONING: "SRCC/LOGICAL_REASONING",
  },

  MORE: "MORE",
};
